spring:
  application:
          name: eureka-consumer

server:
  port: 8183

eureka:
  client:
   serviceUrl:
    defaultZone:  http://localhost:8181/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}


management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
